import type { Location } from "./types";

export const locations: Location[] = [
  {
    slug: "rifthold",
    name: "Rifthold",
    region: "Adarlan",
    image: "/images/locations/rifthold.jpg",
    blurb:
      "Capital of Adarlan — glass, smoke, and empire. Canals cut through a city of informants, assassins, and the quiet terror of a magic-starved kingdom.",
    aesthetics: ["smoked glass", "cold canals", "imperial banners", "night markets"],
    askPrompt: "Tell me about Rifthold",
    rulingPower: "Adarlan (Havilliard crown)",
    climate: "Temperate, often grey — fog over water",
    significance: "Heart of Book 1's competition and Adarlan's political machine.",
    accent: "#64748b",
  },
  {
    slug: "glass-castle",
    name: "The Glass Castle",
    region: "Rifthold · Adarlan",
    image: "/images/locations/rifthold.jpg",
    blurb:
      "Crystalline seat of Adarlan's throne — beautiful enough to hypnotize, cold enough to kill. Champions fight in its shadow; secrets live in its walls.",
    aesthetics: ["crystal towers", "throne light", "polished stone", "mirrored corridors"],
    askPrompt: "Tell me about the Glass Castle",
    rulingPower: "King of Adarlan",
    climate: "Indoor chill; court heat elsewhere",
    significance: "Primary stage for early-series court intrigue and the champion's trials.",
    accent: "#94a3b8",
  },
  {
    slug: "terrasen",
    name: "Terrasen (Orynth)",
    region: "North",
    image: "/images/locations/terrasen.jpg",
    blurb:
      "Pine, stone, and stubborn green — Aelin's homeland. Orynth waits beneath the Staghorn Mountains like a crown waiting to be claimed.",
    aesthetics: ["evergreens", "mountain cold", "ash and rebirth", "old stone halls"],
    askPrompt: "Tell me about Terrasen",
    rulingPower: "Galathynius line (contested)",
    climate: "Harsh winters, forest breath",
    significance: "The kingdom worth burning for — and rebuilding.",
    accent: "#9db4c8",
  },
  {
    slug: "endovier",
    name: "Endovier",
    region: "Adarlan's north",
    image: "/images/locations/endovier.jpg",
    blurb:
      "Salt mines that break bodies and names. The place Celaena crawls out of — and never fully leaves behind.",
    aesthetics: ["white salt scars", "bleak mountains", "chains", "grey light"],
    askPrompt: "Tell me about Endovier",
    rulingPower: "Adarlan labor camps",
    climate: "Bitter, mineral wind",
    significance: "Origin wound of the assassin who becomes a queen.",
    accent: "#a8a29e",
  },
  {
    slug: "doranelle",
    name: "Doranelle",
    region: "Fae realm",
    image: "/images/locations/doranelle.jpg",
    blurb:
      "Maeve's seat — beauty sharpened into a weapon. Rivers of starlight, courts that smile while they bind you.",
    aesthetics: ["moonlit rivers", "pale palaces", "uncanny beauty", "shadowed thrones"],
    askPrompt: "Tell me about Doranelle",
    rulingPower: "Maeve, Queen of the Fae",
    climate: "Eternal twilight moods",
    significance: "Cadre, blood oaths, and immortal politics.",
    accent: "#818cf8",
  },
  {
    slug: "morath",
    name: "Morath",
    region: "South of Adarlan",
    image: "/images/locations/morath.jpg",
    blurb:
      "Black-mountain fortress of nightmares — ilken, collars, and experiments that should never see daylight.",
    aesthetics: ["black stone", "sickly green magic", "oppressive dark", "mountain teeth"],
    askPrompt: "Tell me about Morath",
    rulingPower: "Perrington / Erawan",
    climate: "Ashen, wrong",
    significance: "Factory of Valg horror and southern war engine.",
    accent: "#14532d",
  },
  {
    slug: "wendlyn",
    name: "Wendlyn / Varese",
    region: "Across the sea",
    image: "/images/locations/wendlyn.jpg",
    blurb:
      "Where magic never fully died. Misty coasts, Ashryver courts, and the forests that teach fire how to be more than rage.",
    aesthetics: ["sea cliffs", "mist and moss", "Fae groves", "dawn training yards"],
    askPrompt: "Tell me about Wendlyn",
    rulingPower: "House Ashryver",
    climate: "Soft rains, green breath",
    significance: "Heir of Fire's crucible — identity and power remade.",
    accent: "#34d399",
  },
  {
    slug: "eyllwe",
    name: "Eyllwe",
    region: "Southwest",
    image: "/images/locations/wendlyn.jpg",
    blurb:
      "Nehemia's homeland — resistance, river kingdoms, and a magic tradition Adarlan tried to erase.",
    aesthetics: ["river light", "warm stone", "resistance banners", "ink and wyrd"],
    askPrompt: "Tell me about Eyllwe",
    rulingPower: "Eyllwe royalty (pressured by Adarlan)",
    climate: "Warm, fertile",
    significance: "Friendship, betrayal, and the cost of speaking truth to empire.",
    accent: "#f59e0b",
  },
  {
    slug: "antica",
    name: "Antica / Torre Cesme",
    region: "Southern Continent",
    image: "/images/locations/antica.jpg",
    blurb:
      "Jewel of the khaganate — heat, scholarship, and the Torre Cesme's healing light. Ruks wheel above gold domes.",
    aesthetics: ["sunlit domes", "desert edge", "healing halls", "ruk wings"],
    askPrompt: "Tell me about Antica",
    rulingPower: "The Khaganate",
    climate: "Desert heat, sea breeze",
    significance: "Tower of Dawn's stage — healing as warfare's twin.",
    accent: "#e8a05c",
  },
  {
    slug: "skulls-bay",
    name: "Skull's Bay",
    region: "Pirate isles",
    image: "/images/locations/western-wastes.jpg",
    blurb:
      "Pirate stronghold of Skull's Bay — contracts, betrayal, and the salt taste of freedom bought with blood.",
    aesthetics: ["ship masts", "salt wind", "tavern light", "black sails"],
    askPrompt: "Tell me about Skull's Bay",
    rulingPower: "Pirate lords (Rolfe's waters)",
    climate: "Tropical salt air",
    significance: "Assassin's Blade — early lessons in how dirty a job can get.",
    accent: "#0e7490",
  },
  {
    slug: "oakwald",
    name: "Oakwald Forest",
    region: "Terrasen",
    image: "/images/locations/terrasen.jpg",
    blurb:
      "Ancient woods of Terrasen — green cathedral, hiding place, and memory of a kingdom that refuses to die quietly.",
    aesthetics: ["deep canopy", "moss light", "stag paths", "quiet snow"],
    askPrompt: "Tell me about Oakwald Forest",
    rulingPower: "Wild Terrasen",
    climate: "Cool forest shade",
    significance: "Refuge, route, and northern soul.",
    accent: "#166534",
  },
  {
    slug: "ferian-gap",
    name: "Ferian Gap",
    region: "Witch territory",
    image: "/images/locations/western-wastes.jpg",
    blurb:
      "Wind-scoured pass where Ironteeth hosts break wyverns — red dust, iron sky, and no room for softness.",
    aesthetics: ["dust storms", "wyvern wings", "iron bone", "empty horizon"],
    askPrompt: "Tell me about the Ferian Gap",
    rulingPower: "Ironteeth witch clans",
    climate: "Harsh, dry wind",
    significance: "Manon's proving ground.",
    accent: "#b91c1c",
  },
  {
    slug: "red-desert",
    name: "The Red Desert",
    region: "Silent Assassins' sands",
    image: "/images/locations/antica.jpg",
    blurb:
      "Exile sands where Silent Assassins train — heat, discipline, and debts that echo for years.",
    aesthetics: ["red dunes", "mirage heat", "blade camps", "night cold"],
    askPrompt: "Tell me about the Red Desert",
    rulingPower: "Silent Assassins",
    climate: "Scorching days, freezing nights",
    significance: "Assassin's Blade — forging beyond Arobynn's Keep.",
    accent: "#c45c26",
  },
];

export function getLocation(slug: string) {
  return locations.find((l) => l.slug === slug);
}
