import type { Villain } from "./types";

export const villains: Villain[] = [
  {
    slug: "king-of-adarlan",
    name: "The King of Adarlan",
    shortName: "King of Adarlan",
    titles: ["Conqueror of Erilea", "Banisher of Magic"],
    image: "/images/villains/king-of-adarlan.png",
    blurb:
      "The tyrant who outlawed magic and crushed kingdoms beneath Adarlan's boot. Much of his cruelty is later revealed as a mask for something older wearing a human crown.",
    affiliation: "Adarlan / Valg influence",
    domain: "Rifthold · Glass Castle",
    motivations:
      "Empire, control, and the eradication of magic, until the truth of who holds the reins emerges.",
    conflicts: [
      "Aelin / Celaena",
      "Dorian Havilliard",
      "Terrasen's fall",
      "Magic-users across Erilea",
    ],
    askPrompt: "Who is the King of Adarlan?",
    mood: "shadow",
    accent: "#6b7280",
    minBook: 1,
  },
  {
    slug: "erawan",
    name: "Erawan",
    shortName: "Erawan",
    titles: ["Valg King", "Lord of Morath"],
    image: "/images/villains/erawan.png",
    blurb:
      "One of the three Valg kings, the true darkness behind Adarlan's conquest. Ilken, collars, and black-stone fortresses are tools in a war older than the mortal map.",
    affiliation: "Valg",
    domain: "Morath",
    motivations:
      "Dominion over Erilea and the unmaking of free will through Valg corruption.",
    conflicts: [
      "Aelin Galathynius",
      "Dorian Havilliard",
      "The Crochans and Ironteeth",
      "Anyone who still remembers magic",
    ],
    askPrompt: "Who is Erawan?",
    mood: "void",
    accent: "#14532d",
    minBook: 4,
  },
  {
    slug: "maeve",
    name: "Maeve",
    shortName: "Maeve",
    titles: ["Queen of the Fae", "Queen of Doranelle"],
    image: "/images/villains/maeve.png",
    blurb:
      "Immortal Fae queen of Doranelle, beautiful as a blade and twice as sharp. She collects warriors with blood oaths and plays the long game across centuries.",
    affiliation: "Doranelle · Valg-touched legacy",
    domain: "Doranelle",
    motivations:
      "Power, control of the Cadre, and secrets older than her glittering court admits.",
    conflicts: [
      "Aelin",
      "Rowan and the Cadre",
      "Lorcan",
      "Anyone who threatens her myths",
    ],
    askPrompt: "Who is Maeve?",
    mood: "shadow",
    accent: "#312e81",
    minBook: 3,
  },
  {
    slug: "duke-perrington",
    name: "Duke Perrington",
    shortName: "Perrington",
    titles: ["Duke of Morath", "Overseer of the South"],
    image: "/images/villains/duke-perrington.png",
    blurb:
      "Adarlan's southern fist, builder of nightmares at Morath and architect of experiments best left unnamed. His true allegiance is darker than court gossip suggests.",
    affiliation: "Adarlan / Valg",
    domain: "Morath",
    motivations: "Power through science, shadowfire, and the Valg's designs.",
    conflicts: [
      "Kaltain Rompier",
      "Aelin's court",
      "The people of the southern marches",
    ],
    askPrompt: "Who is Duke Perrington?",
    mood: "void",
    accent: "#3f3f46",
    minBook: 2,
  },
  {
    slug: "kaltain",
    name: "Kaltain Rompier",
    shortName: "Kaltain",
    titles: ["Lady Rompier", "Shadowfire"],
    image: "/images/villains/kaltain.png",
    blurb:
      "A court climber reshaped into a weapon. Shadowfire and captivity rewrite who she is, and what she chooses to burn.",
    affiliation: "Adarlan court to Valg-touched",
    domain: "Rifthold / Morath",
    motivations:
      "Survival, revenge, and reclaiming agency after being used as a vessel.",
    conflicts: ["Duke Perrington", "Court rivals", "The machine of Morath"],
    askPrompt: "Who is Kaltain Rompier?",
    mood: "shadow",
    accent: "#581c87",
    minBook: 1,
  },
  {
    slug: "arobynn",
    name: "Arobynn Hamel",
    shortName: "Arobynn",
    titles: ["King of the Assassins", "Mentor of Celaena"],
    image: "/images/villains/arobynn.png",
    blurb:
      "Rifthold's assassin king: polished, possessive, and expert at turning love into leverage. Early books wear his fingerprints.",
    affiliation: "Assassins' Guild · Rifthold underworld",
    domain: "Assassin's Keep, Rifthold",
    motivations: "Control of Celaena, wealth, and the Guild's supremacy.",
    conflicts: ["Celaena Sardothien", "Sam Cortland", "Guild rivals"],
    askPrompt: "Who is Arobynn Hamel?",
    mood: "shadow",
    accent: "#78350f",
    minBook: 0.5,
  },
  {
    slug: "cairn",
    name: "Cairn",
    shortName: "Cairn",
    titles: ["Witch hunter", "Valg-aligned tormentor"],
    image: "/images/villains/cairn.png",
    blurb:
      "A sadist wrapped in duty, hunting witches and serving darker masters. Cruelty is not a side effect for him. It is the point.",
    affiliation: "Valg-aligned · Maeve's tools",
    domain: "Doranelle's shadow work",
    motivations: "Pain, obedience to power, and breaking those Maeve wants broken.",
    conflicts: ["Aelin", "Fenrys", "Anyone caught in Maeve's nets"],
    askPrompt: "Who is Cairn?",
    mood: "void",
    accent: "#44403c",
    minBook: 6,
  },
  {
    slug: "vernon",
    name: "Vernon Lochan",
    shortName: "Vernon",
    titles: ["Lord of Perranth (usurper)", "Elide's uncle"],
    image: "/images/villains/vernon.png",
    blurb:
      "A small man with large appetites for power. He steals Perranth's future and treats Elide as an obstacle to be sold.",
    affiliation: "Adarlan-aligned nobility",
    domain: "Perranth",
    motivations: "Titles, wealth, and favor from darker powers that promise both.",
    conflicts: ["Elide Lochan", "Lorcan", "The true heirs of Perranth"],
    askPrompt: "Who is Vernon Lochan?",
    mood: "shadow",
    accent: "#57534e",
    minBook: 5,
  },
];

export function getVillain(slug: string) {
  return villains.find((v) => v.slug === slug);
}
