import type { Villain } from "./types";

export const villains: Villain[] = [
  {
    slug: "king-of-adarlan",
    name: "The King of Adarlan",
    shortName: "King of Adarlan",
    titles: ["Conqueror of Erilea", "Banisher of Magic"],
    image: "/images/locations/rifthold.jpg",
    blurb:
      "The tyrant who outlawed magic and crushed kingdoms beneath Adarlan's boot. Much of his cruelty is later revealed as a mask for something older and colder wearing a human crown.",
    affiliation: "Adarlan / Valg influence",
    domain: "Rifthold · Glass Castle",
    motivations: "Empire, control, and the eradication of magic — until the truth of who holds the reins emerges.",
    conflicts: ["Aelin / Celaena", "Dorian Havilliard", "Terrasen's fall", "Magic-users across Erilea"],
    askPrompt: "Who is the King of Adarlan?",
    accent: "#6b7280",
    minBook: 1,
  },
  {
    slug: "erawan",
    name: "Erawan",
    shortName: "Erawan",
    titles: ["Valg King", "Lord of Morath"],
    image: "/images/locations/morath.jpg",
    blurb:
      "One of the three Valg kings — the true darkness behind Adarlan's conquest. Ilken, collars, and black-stone fortresses are tools in a war older than the mortal map.",
    affiliation: "Valg",
    domain: "Morath",
    motivations: "Dominion over Erilea and the unmaking of free will through Valg corruption.",
    conflicts: ["Aelin Galathynius", "Dorian Havilliard", "The Crochans & Ironteeth", "Anyone who still remembers magic"],
    askPrompt: "Who is Erawan?",
    accent: "#14532d",
    minBook: 4,
  },
  {
    slug: "maeve",
    name: "Maeve",
    shortName: "Maeve",
    titles: ["Queen of the Fae", "Queen of Doranelle"],
    image: "/images/characters/maeve.jpg",
    blurb:
      "Immortal Fae queen of Doranelle — beautiful as a blade and twice as sharp. She collects warriors with blood oaths and plays the long game across centuries.",
    affiliation: "Doranelle · Valg-touched legacy",
    domain: "Doranelle",
    motivations: "Power, control of the Cadre, and secrets older than her glittering court admits.",
    conflicts: ["Aelin", "Rowan & the Cadre", "Lorcan", "Anyone who threatens her myths"],
    askPrompt: "Who is Maeve?",
    accent: "#312e81",
    minBook: 3,
  },
  {
    slug: "duke-perrington",
    name: "Duke Perrington",
    shortName: "Perrington",
    titles: ["Duke of Morath", "Overseer of the South"],
    image: "/images/locations/morath.jpg",
    blurb:
      "Adarlan's southern fist — builder of nightmares at Morath and architect of experiments best left unnamed. His true allegiance is darker than court gossip suggests.",
    affiliation: "Adarlan / Valg",
    domain: "Morath",
    motivations: "Power through science, shadowfire, and the Valg's designs.",
    conflicts: ["Kaltain Rompier", "Aelin's court", "The people of the southern marches"],
    askPrompt: "Who is Duke Perrington?",
    accent: "#3f3f46",
    minBook: 2,
  },
  {
    slug: "kaltain",
    name: "Kaltain Rompier",
    shortName: "Kaltain",
    titles: ["Lady Rompier", "Shadowfire"],
    image: "/images/locations/rifthold.jpg",
    blurb:
      "A court climber reshaped into a weapon. Shadowfire and captivity rewrite who she is — and what she chooses to burn.",
    affiliation: "Adarlan court → Valg-touched",
    domain: "Rifthold / Morath",
    motivations: "Survival, revenge, and reclaiming agency after being used as a vessel.",
    conflicts: ["Duke Perrington", "Court rivals", "The machine of Morath"],
    askPrompt: "Who is Kaltain Rompier?",
    accent: "#581c87",
    minBook: 1,
  },
  {
    slug: "arobynn",
    name: "Arobynn Hamel",
    shortName: "Arobynn",
    titles: ["King of the Assassins"],
    image: "/images/locations/rifthold.jpg",
    blurb:
      "Celaena's mentor and the Guild's glittering poison. He teaches her to kill — and to owe him everything.",
    affiliation: "Assassin's Guild · Rifthold",
    domain: "Assassin's Keep",
    motivations: "Control of the Guild, profit, and ownership of his prize pupil.",
    conflicts: ["Celaena Sardothien", "Sam Cortland", "Anyone who challenges his Keep"],
    askPrompt: "Who is Arobynn Hamel?",
    accent: "#78350f",
    minBook: 0.5,
  },
  {
    slug: "cairn",
    name: "Cairn",
    shortName: "Cairn",
    titles: ["Hunter", "Maeve's creature"],
    image: "/images/locations/doranelle.jpg",
    blurb:
      "A sadist in service of immortal power — the kind of enemy who turns captivity into a craft.",
    affiliation: "Doranelle / Maeve",
    domain: "Doranelle's dark corners",
    motivations: "Cruelty as loyalty; serving Maeve's will.",
    conflicts: ["Aelin Galathynius", "Rowan Whitethorn"],
    askPrompt: "Who is Cairn?",
    accent: "#44403c",
    minBook: 5,
  },
  {
    slug: "vernon",
    name: "Vernon Lochan",
    shortName: "Vernon",
    titles: ["Lord of Perranth (usurper)"],
    image: "/images/locations/terrasen.jpg",
    blurb:
      "Elide's uncle — a small, vicious man who mistakes cruelty for strength and Perranth for his birthright.",
    affiliation: "Adarlan's collaborators",
    domain: "Perranth",
    motivations: "Power, status, and erasing the true Lochan line.",
    conflicts: ["Elide Lochan", "Marion Lochan's memory", "Anyone loyal to Terrasen"],
    askPrompt: "Who is Vernon Lochan?",
    accent: "#57534e",
    minBook: 3,
  },
];

export function getVillain(slug: string) {
  return villains.find((v) => v.slug === slug);
}
